### ISSUE TITLE
Joining a game

### ISSUE THREAD

**Issue by Wuts0n** [SpleefLeague/SuperSpleef#13]
I think this is only when accepting a challenge. Occasionally immediately after accepting a challenge the player is kicked for a reason that I've never seen other than in these circumstances (can't remember specifically but it's similar to the "Exception" kick). I've had it where only one player is kicked and the other therefore wins the game as well as both players getting kicked at the same time. As far as I can remember this has only happened on (surprise) quarry but I might be wrong.

**Comment by Jobarion** [comment]
This is probably happening due to a bug in the ChunkPacket injection. Since it is complex to fix and currently quite rare, it is not worth fixing for now.
