### ISSUE TITLE
TeamSpleef scoreboard not showing all teams correctly

### ISSUE THREAD

**Issue by WouterG** [SpleefLeague/SuperSpleef#2]
See: [imgur image](http://i.imgur.com/1tGW9lI.png)

**Comment by Jobarion** [comment]
Not seeing the issue here

**Comment by WouterG** [comment]
Oh there's 1 team missing in this list, sometimes it only shows red and blue, and sometimes no teams at all, and just the "playing to: 5" thing.

**Comment by WouterG** [comment]
More: [imgur](http://i.imgur.com/pqRxQ6s.png)

**Comment by Jobarion** [comment]
This is fixed as far as I know
