### ISSUE TITLE
Broken scores

### ISSUE THREAD

**Issue by Wuts0n** [SpleefLeague/SuperSpleef#8]
When a game finishes there is the possibility of the point not seeming to count and therefore the losing player ends up in spectator mode while the other stays ig with the score counter reading "Player A - 5, Playing to - 5, Player B - 3". Seems to mostly happen on quarry and sometimes desert but I think its possible on a lot of maps and it may be different for some people.

**Comment by Jobarion** [comment]
Could not reproduce
